version: '3.7'
networks:
    default:
        driver: bridge
        name: basic
    elastic:
        driver: bridge
        name: elastic
volumes:
    mongo-data:
        driver: local
        name: mongo-data
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
            - 80:80
            - 443:443
            - 27016:27016
            - 6378:6378
            - 3305:3305
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./nginx/sources.list:/etc/apt/sources.list
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/conf.tcp.d:/etc/nginx/conf.tcp.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - default
            - elastic
    mysql-5.7:
        container_name: mysql
        image: mysql:5.7.36
        restart: always
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - default
        environment:
            - MYSQL_ROOT_PASSWORD=123456
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        expose:
            - 27017
        networks:
            - default
        command: mongod --config /etc/mongo/mongod.conf
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./mongo:/etc/mongo
            - ./mongo/logs/:/var/log/mongodb/
            - mongo-data:/data/db
            - mongo-data:/data/configdb
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        expose:
            - 6379
        networks:
            - default
        entrypoint: redis-server /etc/redis/redis.conf
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
    gitlab-runner:
        container_name: gitlab-runner
        image: gitlab/gitlab-runner:latest
        ports:
            - 8093:8093
        networks:
            - default
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # - ./gitlab/runner:/etc/gitlab-runner
            # docker容器管理器
    portainer:
        container_name: portainer
        image: portainer/portainer
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default
