version: '3.7'
networks:
    chnet:
        driver: bridge
        name: chnet
volumes:
    ch-data:
        driver: local
        name: ch-data
services:
    ch-server:
        container_name: ch-server
        image: clickhouse/clickhouse-server:23.2.3.17
        restart: always
        ports:
            - 18123:8123
            - 19000:9000
            - 19100:9100
        expose:
            - 8123
            - 9000
            - 9100
        environment:
            - CLICKHOUSE_UID=root
            - CLICKHOUSE_GID=root
            # - CLICKHOUSE_DB=cbh_test
            # - CLICKHOUSE_USER=cbh_test
            # - CLICKHOUSE_PASSWORD=cbh_test
            # - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ch-data:/var/lib/clickhouse
            - ./logs:/var/log/clickhouse-server
            - ./config/:/etc/clickhouse-server/
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - chnet
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
