server {
    listen       80;
    listen  [::]:80;
    server_name  openclaw.jpc-hp;

    location / {
        # 转发到本地端口
        proxy_pass http://host.docker.internal:18789;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

